#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/en/2/20/GTVBangladeshLogo.png", Gazi Tv
http://10.28.28.2:8080/roarzone/1/index.m3u8?token=2e634155973f91e60043847c44c95f374a82a20b-65aad19e66d00a4fb91662a604e3ae7b-1667049494-1667038694


#EXTINF:-1 tvg-name="T SPORTS" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/1/11/T_Sports_logo.png/200px-T_Sports_logo.png",T SPORTS
http://10.28.28.2:8080/roarzone/102/index.m3u8?token=7b94d7b3fb961c1ac1d9b28dc4a1bd5bcd4d0eff-64475ed1017100f4d13cd45c6215f9e9-1667049593-1667038793

#EXTINF:-1 tvg-name="Nagorik TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/2/24/Nagorik_TV_Logo.png/150px-Nagorik_TV_Logo.png" ,Nagorik TV
http://10.28.28.2:8080/roarzone/59/tracks-v1a1/mono.m3u8?token=abdf7795fe1b923ef015a6469f357f82e28e6e01-ec26509fb592ec64518daf9d5dd5e752-1667049634-1667038834

#EXTINF:-1 tvg-name="Star Sports 1 HD" tvg-logo="https://i.ibb.co/GxSmPCF/STAR-Sports-1-logo.png" group-title="Sports",Star Sports 1 HD
http://10.28.28.2:8080/roarzone/25/tracks-v1a1/mono.m3u8?token=55ab53e1b50df3466113b66a54eb7013bac99972-219e85364331183b2fa1800b9dd9b113-1667049678-1667038878

#EXTINF:-1 tvg-name="Star Sports Select 1 HD" tvg-logo="https://i.ibb.co/BBm0vcP/Star-Sports-Select-1.jpg" group-title="Sports",Star Sports Select 1 HD
http://10.28.28.2:8080/roarzone/27/index.m3u8?token=780f0f4c01048d881322ba6f70e75a4d7a71d8eb-6d30f5bb826b2099fa71473fab02955d-1667050199-1667039399

#EXTINF:-1 tvg-name="Star Sports 2 HD" tvg-logo="https://i.ibb.co/S7N3YWn/star-sports-select-hd-2-logo-300x300.jpg" group-title="Sports",Star Sports 2 HD
http://10.28.28.2:8080/roarzone/28/index.m3u8?token=074375f068cca0610a5ac1157c06dc197c7037fb-1f0689f99a036913a547c7e9a7ab7ce0-1667050225-1667039425

#EXTINF:-1 tvg-name="Sony Ten 1" tvg-logo="https://www.indiantvinfo.com/media/2020/09/Sony-Ten-1-HD-Channel.png" group-title="Sports",Sony Ten 1
http://10.28.28.2:8080/roarzone/20/index.m3u8?token=785217b5caa83338db55184a66c6530f4b95e1b3-672578d7658b6e8798e9d367deaffe62-1667050018-1667039218

#EXTINF:-1 tvg-name="Sony Ten 2 " tvg-logo="https://www.tvchannelpricelist.com/wp-content/uploads/channels-logo-300/sony-ten-2-logo-300x300.jpg" group-title="Sports",Sony Ten 2 
http://10.28.28.2:8080/roarzone/21/index.m3u8?token=6ad19b59e34613bec66203b2be6d3879d8f85ec7-841ff4cc68b9c0b6bae968d1d5fbeb51-1667050049-1667039249

#EXTINF:-1 tvg-name="Sony Ten 3" tvg-logo="https://vignette.wikia.nocookie.net/logopedia/images/6/6c/Sony_Ten_3.png/revision/latest?cb=20170818190243" group-title="Sports",Sony Ten 3
http://10.28.28.2:8080/roarzone/22/index.m3u8?token=58e67ca652d7e69fbb7c92001b0fe6951351402c-c0c3e4e8700086a1d8f7925da3d5d481-1667050071-1667039271

#EXTINF:-1 tvg-name="Sony Six" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Sony_six_logo.png/200px-Sony_six_logo.png" group-title="Sports",Sony Six
http://10.28.28.2:8080/roarzone/24/index.m3u8?token=10614cf38c20d569f87654a69037663c208189f5-bc14f38892549c6c9542deff4a860ff1-1667049956-1667039156


EXTINF:-1 tvg-name="Sony ESPN" tvg-logo="https://i.ibb.co/KrhjWX7/Sony-ESPN.png" group-title="Sports",Sony ESPN
http://10.28.28.2:8080/roarzone/23/index.m3u8?token=b6036543948be7285d7b68140ca7653c45f55dc1-d9cf437767a5ecfbf9034225591b6f19-1667050110-1667039310


#EXTINF:-1 tvg-name="PTV Sports" tvg-logo="https://i.ibb.co/vdhYgt8/Ptv-Sports-Latest-Frequency-On-Paksat-38-E-2016.png" group-title="Sports",PTV Sports
http://10.28.28.2:8080/roarzone/73/index.m3u8?token=0f300c6de4952e4752d1122cf0fd55f4b367152a-b834e9c204878e49d9bc02fa9a9798ff-1667050254-1667039454



#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="MAASRANGA TV" tvg-logo="https://i.ibb.co/mqV2CL0/Maasranga-Television-Logo.jpg",MAASRANGA TV
http://10.28.28.2:8080/roarzone/51/index.m3u8?token=a8169a5586544fa13f4f097c6cc5fbd605f21bda-1b8d4e311531e0973aaaa687f04b1fd6-1663147306-1663136506


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="DURONTO TV" tvg-logo="https://i.ibb.co/7rx1bNz/Duronto.png" group-title="Kids",DURONTO TV
http://10.28.28.2:8080/roarzone/10/index.m3u8?token=caf300bc73b3641d29b6a019e077de816f575365-7f9267b462fb03011726dfc7e40c4fdc-1667050360-1667039560

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Cartoon Network" tvg-logo="https://i.ibb.co/hHLJ9GG/54.jpg" group-title="Kids",Cartoon Network
http://10.28.28.2:8080/roarzone/79/index.m3u8?token=96b1a0e75dab837e1ad3ff4a72487c541e983685-8b8a041b86d9b99b7b5bd3eb96f34fbe-1667050383-1667039583




#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Independent" tvg-logo="https://www.pngitem.com/pimgs/m/21-212855_independent-tv-logo-png-transparent-png.png" group-title="Bangla News",Independent
http://10.28.28.2:8080/roarzone/12/index.m3u8?token=192609f0b0519631654d715e5778c6040bb5d041-62185f7c8cf4c1893cdded5d0d82dd89-1667050420-1667039620


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="JAMUNA TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/JamunaTV_logo.jpg/250px-JamunaTV_logo.jpg" group-title="Bangla News" ,JAMUNA TV
http://10.28.28.2:8080/roarzone/13/index.m3u8?token=148d3ab1821e9e352ea9fe8004183e351fe8e2ee-b562c73745527df1299f96469f5cd937-1667050446-1667039646

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Ekattor" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/5/57/Ekattor_TV_logo.svg/190px-Ekattor_TV_logo.svg.png" group-title="Bangla News",Ekattor
http://10.28.28.2:8080/roarzone/11/index.m3u8?token=bb4f9f910e935a6c6edf083cc7d67ef8f6aa4f7a-9e874405d172cad22d6ef8a392bb4620-1667050478-1667039678

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="SOMOY TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/d/d7/Somoy_TV_logo.png" group-title="Bangla News" ,SOMOY NEWS
http://10.28.28.2:8080/roarzone/17/index.m3u8?token=d8337eae4de076d5e11ccdf2948cbf36a13ac664-e08de8115321b81bf984434c77c6fb31-1667050508-1667039708

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Channel I" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/8/88/Channel-i.svg/192px-Channel-i.svg.png",CHANNEL I
http://223.29.212.14:8080/roarzone/6/index.m3u8?token=b57bbdfdc856eeba1ca7236277ebf455e30b9749-14ff532a0c126d23d04a422e0dd1bfd8-1662367116-1662356316

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="NEWS24" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/0/00/News24logo%28BD%29.jpg/200px-News24logo%28BD%29.jpg",NEWS 24
http://223.29.212.14:8080/roarzone/18/index.m3u8?token=4e9214fd3aef7a635464668f571e2cd7b4449268-d5021b50ea6654d273fd15cbec1f6c63-1662367204-1662356404



#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="ETV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/d/d9/Ekushey_Television_Logo.svg/200px-Ekushey_Television_Logo.svg.png",EKUSHEY TELEVISION
http://223.29.212.14:8080/roarzone/65/index.m3u8?token=375d4d99e2ea0a81f275c6ec4717b638bbdf5d4c-03cbf0ef4766184f5e69cac924efc9c3-1662367351-1662356551

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="CHANNEL 24" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Channel24logo.svg/200px-Channel24logo.svg.png",CHANNEL 24
http://223.29.212.14:8080/roarzone/5/index.m3u8?token=043199c197b37f3a8f6bd20ead2f5ac5cd583014-70ec94b8580d35c4c9d3fefeea725cc9-1662367442-1662356642

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="RTV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Rtv_bangladesh.svg/240px-Rtv_bangladesh.svg.png",RTV
http://223.29.212.14:8080/roarzone/14/index.m3u8?token=18225b8f1ad3c0da624355ada38f2a3825e8d04d-5aa5a33a72de315194d3389e53640b13-1662367548-1662356748

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="NTV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/e/ef/NTV_%28Bangladesh%29_logo.svg/200px-NTV_%28Bangladesh%29_logo.svg.png",NTV
http://223.29.212.14:8080/roarzone/54/index.m3u8?token=d4e17d5962d5875b3d7d1930b91d4da254cb19c5-2df8a41e3064095336f42a861f672117-1662367615-1662356815

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Banglavision" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/1/1d/Banglavision.svg/120px-Banglavision.svg.png",Banglavision
http://223.29.212.14:8080/roarzone/3/index.m3u8?token=900ff6f02567d0c3c9af32161381cf67cf21d8e1-9ecdf964f9af34697ed658bedc0a2f23-1662368092-1662357292

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="ATN Bangla" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/ATN_Bangla.svg/200px-ATN_Bangla.svg.png",ATN Bangla
http://223.29.212.14:8080/roarzone/2/index.m3u8?token=16139deeb0f179202b77875348b635cf6c78ff12-54e9b42ea5a0a698bb8e7eb453f89a4a-1662368208-1662357408

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Channel 9" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/f/ff/Channel9_bd.svg/200px-Channel9_bd.svg.png",Channel 9 
http://223.29.212.14:8080/roarzone/4/index.m3u8?token=405f14feba12632ecd651565906a19f56bbc0d4d-731ce99d6520b12ee98c6117800e159d-1662368277-1662357477

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="DBC News" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/9/99/DBC_News_Logo.svg/250px-DBC_News_Logo.svg.png",DBC News
http://223.29.212.14:8080/roarzone/7/index.m3u8?token=b53f0b84f4dc1e831d8688121c183c325faa05d0-cdb86217730f37f1926d7217004a0cd5-1662368370-1662357570

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="My TV " tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/b/b1/My_TV_Logo.svg/260px-My_TV_Logo.svg.png",My TV 
http://223.29.212.14:8080/roarzone/56/index.m3u8?token=8364df935bf0f90d5ed459ecb641fb3c5e36b1c2-ff6dd4aa538ea1660a00db3eeaaf9151-1662368464-1662357664

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Deepto TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/3/31/Deepto_TV_logo.png/240px-Deepto_TV_logo.png",Deepto TV
http://223.29.212.14:8080/roarzone/8/index.m3u8?token=9ace0d0bd3f59ec49bf4f6f4052fc27cc1a08381-d08cdd7376c9cb9367c81c7d4a48d87c-1662368536-1662357736

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="SA TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/1/15/SA_TV_Logo.png",SA TV
http://223.29.212.14:8080/roarzone/15/index.m3u8?token=068c8bc39980d6b5f86d1df73a53af65ecf797ed-073985856c80be5e6f5d25fdeb2281ea-1662368602-1662357802

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Ekattor" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/5/57/Ekattor_TV_logo.svg/190px-Ekattor_TV_logo.svg.png",Ekattor
http://223.29.212.14:8080/roarzone/11/index.m3u8?token=cd6005934cd6a193481216be1066527c0dc7092c-ccfd4e22b8d8d230a8bd9227933e0ace-1662368664-1662357864

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Asian TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Asian_TV_Logo.svg/100px-Asian_TV_Logo.svg.png",Asian TV
http://223.29.212.14:8080/roarzone/62/index.m3u8?token=d310a075251ac8b8311e4362dfab24bc16b79c2b-aa5fc3cc2d8e1efdc69141a0c4f73c2e-1662368730-1662357930

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Boishakhi Television" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Boishakhi_TV_logo.svg/200px-Boishakhi_TV_logo.svg.png",Boishakhi Television
http://223.29.212.14:8080/roarzone/61/index.m3u8?token=7c2b58a2dffdf67873775966901ba2386b6d3b5b-064970a2d213ff7eb696f8b0869a1a83-1662368872-1662358072

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Mohona Television" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/9/94/Mohona_tv_Logo.svg/200px-Mohona_tv_Logo.svg.png",Mohona Television
http://223.29.212.14:8080/roarzone/50/index.m3u8?token=7f16095fab7b40a0a53cf6b314a2b1b5a35d3e0d-d465c5e190c58f76994aeb8e0c2ebda9-1662368961-1662358161

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="BANGLA TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/Bangla_TV_Logo.png/220px-Bangla_TV_Logo.png",BANGLA TV
http://223.29.212.14:8080/roarzone/19/index.m3u8?token=766e473a2ce3ba12bd1500189129de85a1ff24bc-6a046a0d31e3675c6debce2edea4fa51-1662369042-1662358242

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Ananda TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Ananda_TV_Logo.png/220px-Ananda_TV_Logo.png",Ananda TV
http://223.29.212.14:8080/roarzone/16/index.m3u8?token=5d5d82482ba35d32b8004ce03a6ff7f5225896c7-b4d5bfd8117cf0eaaa600de832fa94aa-1662369106-1662358306

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="ATN ISLAMIC" tvg-logo="http://atnislamic.tv/images/logo.png",ATN ISLAMIC
http://223.29.212.14:8080/roarzone/63/index.m3u8?token=359db3b20e83283ce38e80ab4b44f561aa83613d-86a7f783ad996fcbe89d157fe882d12a-1662369164-1662358364

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="ATN NEWS" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/5/53/ATN_News_Logo_3.GIF/120px-ATN_News_Logo_3.GIF",ATN NEWS
http://223.29.212.14:8080/roarzone/49/index.m3u8?token=ab7c05466b68a3e4a6bfaccded15f973502a36ce-464bbb2066869e8df51306b3ff675eb4-1662369336-1662358536

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="MOVIE BANGLA" tvg-logo="https://yt3.ggpht.com/a-/AAuE7mClSnZA1CfOAthQMETSutoM2C6Tzi0lY0yc8w=s900-mo-c-c0xffffffff-rj-k-no",MOVIE BANGLA
http://223.29.212.14:8080/roarzone/19/index.m3u8?token=8903177b56bee7e86a888eb22555aa0240575173-fd4f6c461c57330895eefffa64415f82-1662369420-1662358620

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="DESH TV" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Desh_TV_Logo.svg/200px-Desh_TV_Logo.svg.png",DESH TV
http://223.29.212.14:8080/roarzone/9/index.m3u8?token=1f527f1bd50c79135d2f8d88d250707dcb301c6c-6b657709d3f0c49811d2f250d4fa27f2-1662369544-1662358744

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="COLORS BANGLA" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Colors_Bangla.png/220px-Colors_Bangla.png",COLORS BANGLA
http://223.29.212.14:8080/roarzone/66/index.m3u8?token=d381f52ce2b3073cec3957c6b0a6298340d2f96c-4d86bfe71597d96b7d64a440d437e712-1662369664-1662358864

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Sony Aath" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Sony_Aath_logo.svg/120px-Sony_Aath_logo.svg.png",Sony Aath
http://223.29.212.14:8080/roarzone/33/index.m3u8?token=c8e9ef8739f0dbfb97c312f900f8bbe2289fc2f6-facbc4c3424ec520031970e843c0d59e-1662369832-1662359032

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Zee Bangla" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Zee_Bangla_New_Logo.jpg/200px-Zee_Bangla_New_Logo.jpg",Zee Bangla
http://223.29.212.14:8080/roarzone/34/index.m3u8?token=85ef3cb452a5c700502f26d324c8767aa5346516-fc637a9431f1a77987b31c894dd83021-1662369892-1662359092

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Zee Bangla Cinema" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/8/84/Zee_Bangla_Cinema_Logo.jpg/250px-Zee_Bangla_Cinema_Logo.jpg",Zee Bangla Cinema
http://223.29.212.14:8080/roarzone/29/index.m3u8?token=5d51485fd23d7d4444695f3b587e85cda4818ff7-9f0ceebc59e6b5a683c1f6de5958945f-1662369952-1662359152

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Star Jalsha" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Star_Jalsha_logo.jpg/220px-Star_Jalsha_logo.jpg",Star Jalsha
http://223.29.212.14:8080/roarzone/30/index.m3u8?token=506223ff0d92926c3b70036ad7ce6d14de1c833d-21c02775ec9bb13961d9b0a966949124-1662370056-1662359256

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Star Jalsha Movies" tvg-logo="https://vignette.wikia.nocookie.net/logopedia/images/4/44/Jalsha-movies-hd.jpg/revision/latest?cb=20160524181421",Star Jalsha Movies
http://223.29.212.14:8080/roarzone/31/index.m3u8?token=628a147b3591e600fe2ea4c823528734658f6bbb-cc1d04321065d710341d7dbccece4ae2-1662370103-1662359303

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="HBO" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/220px-HBO_logo.svg.png",HBO
http://223.29.212.14:8080/roarzone/42/index.m3u8?token=48b3c2be4c942e78bdab75778dd9fe1ff0f7b3f7-814910e0f583b68206ba4601c7279616-1662370258-1662359458

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="ZEE ACTION" tvg-logo="https://vignette.wikia.nocookie.net/logopedia/images/4/42/Zee_Action.jpg/revision/latest/scale-to-width-down/220?cb=20171105144346",ZEE ACTION
http://223.29.212.14:8080/roarzone/78/index.m3u8?token=0d854147489e5ab598699962bd216c7877cc7479-6dc7db8b2b793da520a6df20f2ba41a8-1662370318-1662359518

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Sony Pix" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/5/5f/Sony_PIX.png/120px-Sony_PIX.png",Sony Pix
http://223.29.212.14:8080/roarzone/41/index.m3u8?token=747525c97e45322ea8b7b3e7cd84c566a204db23-5f3e5a33f4da5fd829650d11b302e120-1662370468-1662359668

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Star Movies Select HD" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/STAR_Movies_logo.svg/220px-STAR_Movies_logo.svg.png",Star Movies Select HD
http://223.29.212.14:8080/roarzone/39/index.m3u8?token=b954eab738b2f082451c3a11b7412370a230b689-c15e135f420778d78aae30edc3deb00b-1662370640-1662359840

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="BBC World News" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/BBC_World_News_2022_%28Boxed%29.svg/170px-BBC_World_News_2022_%28Boxed%29.svg.png",BBC World News
http://223.29.212.14:8080/roarzone/44/index.m3u8?token=a6090fbf92c772cc869e5efd8571e2a650e23ba2-a8d95aadbed06771fe2b9c30d1928daa-1662370538-1662359738





#EXTINF:-1 tvg-name="Champions TV 1" tvg-logo="https://i.imgur.com/ffWoTF9.png" group-title="Sport",Champions TV 1
http://pprotv.com:80/fahad70/fahad70/39556
#EXTINF:-1 tvg-name="Champions TV 2" tvg-logo="https://i.imgur.com/r2aPCX8.png" group-title="Sport",Champions TV 2
http://tv.zonanime.my.id/vidio/championstv2.m3u8
#EXTINF:-1 tvg-name="Champions TV 3" tvg-logo="https://i.imgur.com/26Jar5R.png" group-title="Sport",Champions TV 3
http://tv.zonanime.my.id/vidio/championstv3.m3u8






#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/en/2/20/GTVBangladeshLogo.png", Gazi Tv
http://10.28.28.2:8080/roarzone/1/index.m3u8?token=2e634155973f91e60043847c44c95f374a82a20b-65aad19e66d00a4fb91662a604e3ae7b-1667049494-1667038694


#EXTINF:-1 tvg-name="T SPORTS" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/1/11/T_Sports_logo.png/200px-T_Sports_logo.png",T SPORTS
http://10.28.28.2:8080/roarzone/102/index.m3u8?token=7b94d7b3fb961c1ac1d9b28dc4a1bd5bcd4d0eff-64475ed1017100f4d13cd45c6215f9e9-1667049593-1667038793

#EXTINF:-1 tvg-name="Nagorik TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/2/24/Nagorik_TV_Logo.png/150px-Nagorik_TV_Logo.png" ,Nagorik TV
http://10.28.28.2:8080/roarzone/59/tracks-v1a1/mono.m3u8?token=abdf7795fe1b923ef015a6469f357f82e28e6e01-ec26509fb592ec64518daf9d5dd5e752-1667049634-1667038834

#EXTINF:-1 tvg-name="Star Sports 1 HD" tvg-logo="https://i.ibb.co/GxSmPCF/STAR-Sports-1-logo.png" group-title="Sports",Star Sports 1 HD
http://10.28.28.2:8080/roarzone/25/tracks-v1a1/mono.m3u8?token=55ab53e1b50df3466113b66a54eb7013bac99972-219e85364331183b2fa1800b9dd9b113-1667049678-1667038878

#EXTINF:-1 tvg-name="Star Sports Select 1 HD" tvg-logo="https://i.ibb.co/BBm0vcP/Star-Sports-Select-1.jpg" group-title="Sports",Star Sports Select 1 HD
http://10.28.28.2:8080/roarzone/27/index.m3u8?token=780f0f4c01048d881322ba6f70e75a4d7a71d8eb-6d30f5bb826b2099fa71473fab02955d-1667050199-1667039399

#EXTINF:-1 tvg-name="Star Sports 2 HD" tvg-logo="https://i.ibb.co/S7N3YWn/star-sports-select-hd-2-logo-300x300.jpg" group-title="Sports",Star Sports 2 HD
http://10.28.28.2:8080/roarzone/28/index.m3u8?token=074375f068cca0610a5ac1157c06dc197c7037fb-1f0689f99a036913a547c7e9a7ab7ce0-1667050225-1667039425

#EXTINF:-1 tvg-name="Sony Ten 1" tvg-logo="https://www.indiantvinfo.com/media/2020/09/Sony-Ten-1-HD-Channel.png" group-title="Sports",Sony Ten 1
http://10.28.28.2:8080/roarzone/20/index.m3u8?token=785217b5caa83338db55184a66c6530f4b95e1b3-672578d7658b6e8798e9d367deaffe62-1667050018-1667039218

#EXTINF:-1 tvg-name="Sony Ten 2 " tvg-logo="https://www.tvchannelpricelist.com/wp-content/uploads/channels-logo-300/sony-ten-2-logo-300x300.jpg" group-title="Sports",Sony Ten 2 
http://10.28.28.2:8080/roarzone/21/index.m3u8?token=6ad19b59e34613bec66203b2be6d3879d8f85ec7-841ff4cc68b9c0b6bae968d1d5fbeb51-1667050049-1667039249

#EXTINF:-1 tvg-name="Sony Ten 3" tvg-logo="https://vignette.wikia.nocookie.net/logopedia/images/6/6c/Sony_Ten_3.png/revision/latest?cb=20170818190243" group-title="Sports",Sony Ten 3
http://10.28.28.2:8080/roarzone/22/index.m3u8?token=58e67ca652d7e69fbb7c92001b0fe6951351402c-c0c3e4e8700086a1d8f7925da3d5d481-1667050071-1667039271

#EXTINF:-1 tvg-name="Sony Six" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Sony_six_logo.png/200px-Sony_six_logo.png" group-title="Sports",Sony Six
http://10.28.28.2:8080/roarzone/24/index.m3u8?token=10614cf38c20d569f87654a69037663c208189f5-bc14f38892549c6c9542deff4a860ff1-1667049956-1667039156


EXTINF:-1 tvg-name="Sony ESPN" tvg-logo="https://i.ibb.co/KrhjWX7/Sony-ESPN.png" group-title="Sports",Sony ESPN
http://10.28.28.2:8080/roarzone/23/index.m3u8?token=b6036543948be7285d7b68140ca7653c45f55dc1-d9cf437767a5ecfbf9034225591b6f19-1667050110-1667039310


#EXTINF:-1 tvg-name="PTV Sports" tvg-logo="https://i.ibb.co/vdhYgt8/Ptv-Sports-Latest-Frequency-On-Paksat-38-E-2016.png" group-title="Sports",PTV Sports
http://10.28.28.2:8080/roarzone/73/index.m3u8?token=0f300c6de4952e4752d1122cf0fd55f4b367152a-b834e9c204878e49d9bc02fa9a9798ff-1667050254-1667039454



#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="MAASRANGA TV" tvg-logo="https://i.ibb.co/mqV2CL0/Maasranga-Television-Logo.jpg",MAASRANGA TV
http://10.28.28.2:8080/roarzone/51/index.m3u8?token=a8169a5586544fa13f4f097c6cc5fbd605f21bda-1b8d4e311531e0973aaaa687f04b1fd6-1663147306-1663136506


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="DURONTO TV" tvg-logo="https://i.ibb.co/7rx1bNz/Duronto.png" group-title="Kids",DURONTO TV
http://10.28.28.2:8080/roarzone/10/index.m3u8?token=caf300bc73b3641d29b6a019e077de816f575365-7f9267b462fb03011726dfc7e40c4fdc-1667050360-1667039560

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Cartoon Network" tvg-logo="https://i.ibb.co/hHLJ9GG/54.jpg" group-title="Kids",Cartoon Network
http://10.28.28.2:8080/roarzone/79/index.m3u8?token=96b1a0e75dab837e1ad3ff4a72487c541e983685-8b8a041b86d9b99b7b5bd3eb96f34fbe-1667050383-1667039583




#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Independent" tvg-logo="https://www.pngitem.com/pimgs/m/21-212855_independent-tv-logo-png-transparent-png.png" group-title="Bangla News",Independent
http://10.28.28.2:8080/roarzone/12/index.m3u8?token=192609f0b0519631654d715e5778c6040bb5d041-62185f7c8cf4c1893cdded5d0d82dd89-1667050420-1667039620


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="JAMUNA TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/JamunaTV_logo.jpg/250px-JamunaTV_logo.jpg" group-title="Bangla News" ,JAMUNA TV
http://10.28.28.2:8080/roarzone/13/index.m3u8?token=148d3ab1821e9e352ea9fe8004183e351fe8e2ee-b562c73745527df1299f96469f5cd937-1667050446-1667039646

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Ekattor" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/5/57/Ekattor_TV_logo.svg/190px-Ekattor_TV_logo.svg.png" group-title="Bangla News",Ekattor
http://10.28.28.2:8080/roarzone/11/index.m3u8?token=bb4f9f910e935a6c6edf083cc7d67ef8f6aa4f7a-9e874405d172cad22d6ef8a392bb4620-1667050478-1667039678

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="SOMOY TV" tvg-logo="https://upload.wikimedia.org/wikipedia/en/d/d7/Somoy_TV_logo.png" group-title="Bangla News" ,SOMOY NEWS
http://10.28.28.2:8080/roarzone/17/index.m3u8?token=d8337eae4de076d5e11ccdf2948cbf36a13ac664-e08de8115321b81bf984434c77c6fb31-1667050508-1667039708








#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="CHANNEL 24" tvg-logo="https://cdn.bongobd.com/upload/channels/landscape/Dh0neKDKLrs.png" group-title="Bangla News",CHANNEL 24
https://tempx.jagobd.com:441/c5V6mmMyX7RpbEU9Mi8xNy8yMDEOGIDU6RgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcGVMZEJCTEFWeVN3PT0mdFsaWRtaW51aiPhnPTI/channel24-sg-e8e.stream/chunks.m3u8


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Ekushey TV" tvg-logo="https://s4.gifyu.com/images/image534fa27d7683f33d.png" group-title="Bangla News",Ekushey TV
http://210.4.72.204/hls-live/livepkgr/_definst_/liveevent/livestream3.m3u8


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="itv" tvg-logo="https://i.ibb.co/0JLNqRC/Itv.jpg" group-title="Bangla News",itv
http://162.244.81.142:1935/live/livestream/playlist.m3u8


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Nandan Tv" tvg-logo="https://play-lh.googleusercontent.com/m7UvZLUj76Gv2Rwvbk1sKYk6ra6zWWmQGkJMCMZtvUME59BH76vU4ScIY0L_qw_qHA" group-title="Bangla News",Nandan Tv
http://nandansyst.com/hls/nandan.m3u8



#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="38.Doyel TV" tvg-logo="" group-title="Bangladesh",38.Doyel TV
https://tempx.jagobd.com:441/c5V6mmMyX7RpbEU9Mi8xNy8yMDEOGIDU6RgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcGVMZEJCTEFWeVN3PT0mdFsaWRtaW51aiPhnPTI/doyeltv.stream/chunks.m3u8



#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="43.MAQ TV" tvg-logo="" group-title="Bangladesh",43.MAQ TV
http://str24.l9574.com/517.stream/index.m3u8



#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="52.Voice TV" tvg-logo="" group-title="Bangladesh",52.Voice TV
https://tempx.jagobd.com:441/c5V6mmMyX7RpbEU9Mi8xNy8yMDEOGIDU6RgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcGVMZEJCTEFWeVN3PT0mdFsaWRtaW51aiPhnPTI/voicetv.stream/chunks.m3u8


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="6.Bangla TV" tvg-logo="" group-title="Bangladesh",6.Bangla TV
https://tempx.jagobd.com:441/c5V6mmMyX7RpbEU9Mi8xNy8yMDEOGIDU6RgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcGVMZEJCTEFWeVN3PT0mdFsaWRtaW51aiPhnPTI/banglatvhd.stream/chunks.m3u8


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="1.Anando TV" tvg-logo="https://i.imgur.com/WpMA9kC.png" group-title="Bangladesh",1.Anando TV
https://tempx.jagobd.com:441/c5V6mmMyX7RpbEU9Mi8xNy8yMDEOGIDU6RgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcGVMZEJCTEFWeVN3PT0mdFsaWRtaW51aiPhnPTI/anandatv.stream/chunks.m3u8



#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="45.Movie Bangla" tvg-logo="" group-title="Bangladesh",45.Movie Bangla
https://tempinfobase.jagobd.com:444/cZVydmVyX8RpbEU9Mi8xNy8yMDE0GIDU6RgzQ6NTAgdEoaeFzbF92YWxIZT00U0ezN1IzMyfvcGVMZEJCTEFWeVN3PTOmdFsaWRtaW51aiPhnPTI/moviebanglalink2.stream/chunks.m3u8


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="52.Voice TV" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/4/4d/VoiceTV.png" group-title="Bangladesh",52.Voice TV
https://tempx.jagobd.com:441/c5V6mmMyX7RpbEU9Mi8xNy8yMDEOGIDU6RgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcGVMZEJCTEFWeVN3PT0mdFsaWRtaW51aiPhnPTI/voicetv.stream/chunks.m3u8



#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="6.Bangla TV" tvg-logo="https://s6.gifyu.com/images/image87250d092deb08a2.png" group-title="Bangladesh",6.Bangla TV
https://tempx.jagobd.com:441/c5V6mmMyX7RpbEU9Mi8xNy8yMDEOGIDU6RgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcGVMZEJCTEFWeVN3PT0mdFsaWRtaW51aiPhnPTI/banglatvhd.stream/chunks.m3u8



#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="itv" tvg-logo="https://i.ibb.co/0JLNqRC/Itv.jpg" group-title="Bangladesh",itv
http://162.244.81.142:1935/live/livestream/playlist.m3u8



#EXTINF:-1 tvg-id="ChannelS.uk" tvg-name="CHANNEL S (4)" tvg-logo="" group-title="Bangladesh",CHANNEL S (4)
https://tempinfobase.jagobd.com:444/cZVydmVyX8RpbEU9Mi8xNy8yMDE0GIDU6RgzQ6NTAgdEoaeFzbF92YWxIZT00U0ezN1IzMyfvcGVMZEJCTEFWeVN3PTOmdFsaWRtaW51aiPhnPTI/chsukoff.stream/chunks.m3u8


#EXTINF:-1 tvg-id="ext" tvg-name="Channel-S (3)" tvg-logo="" group-title="Bangladesh",Channel-S (3)
https://a.jsrdn.com/r-373576a3/publish/22679_24MrQma9TX/index.m3u8


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="ITV IPTV [BD]" tvg-logo="https://i.ibb.co/0JLNqRC/Itv.jpg" group-title="Bangladesh",ITV IPTV [BD]
http://162.244.81.142:1935/live/livestream/playlist.m3u8?@amarnettv.live

#EXTINF:-1 tvg-id="New EPG" tvg-name="NAT GEO" tvg-logo="" group-title="Bangladesh",NAT GEO
http://admdn2.cdn.mangomolo.com/nagtv/smil:nagtv.stream.smil/chunklist_b4000000_t64MTA4MHA=.m3u8


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Al Jazeera" tvg-logo="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTYv63NeTuzF6JQ2e2JnQVpWpcF3c_PtO0-ymSRtcGGaefvMkeq&usqp=CAU" group-title="",Al Jazeera
https://live-hls-web-aje.getaj.net/AJE/03.m3u8



#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="CGTV Documentary" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/d/d6/CGTN_Documentary_logo.png" group-title="",CGTV Documentary
https://livedoc.cgtn.com/1000d/prog_index.m3u8


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="RTP TV" tvg-logo="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRBsRDpDOCl8LWSFDqpw6_ljNRPLBYlnlQqqA&usqp=CAU" group-title="",RTP TV
http://live4.tdm.com.mo/ch2/_definst_//ch2.live/chunklist_w55167431.m3u8


#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="ABC Radio(89.2)" ,ABC Radio(89.2)
http://node-04.zeno.fm/h7n8ug96eeruv?@IPTVSolution
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Big FM" ,Big FM
http://sc-bb.1.fm:8017/;?listening-from-radio-garden=1601016386228
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Bollywood Punjabi Radio" ,Bollywood Punjabi Radio
http://stream.zeno.fm/1k0y9f0cm0quv
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Colours FM" ,Colours FM
http://45.64.135.88:8000/stream1
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Dhaka FM (90.4)" ,Dhaka FM (90.4)
http://118.179.219.244:8000/;stream.mp3?@IPTVSoltuion
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="FnF.FM Bangla" ,FnF.FM Bangla
http://eu6.fastcast4u.com:5099/;stream?listening-from-radio-garden=1601015069589
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Harman Radio Australia" ,Harman Radio Australia
http://harmanradio.net:8000/main_48.mp3
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Jagoo FM" ,Jagoo FM
http://128.199.184.111:12496/;stream/1?listening-from-radio-garden=1601015113662

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Non Stop Hindi Radio" ,Non Stop Hindi Radio
http://198.178.123.14:8216/;
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Radio BollyFm" ,Radio BollyFm
http://stream.radiobollyfm.in:8201/hd?t=1526570335
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Radio Foorti (88.0)" ,Radio Foorti (88.0)
http://119.148.23.88:1021/;?@IPTVSoltuion
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Radio Hindi International" ,Radio Hindi International
http://radio.bongonet.net:8012/rhi
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Radio Ishara" ,Radio Ishara
http://nickerie.webhop.net:8000/;stream.mp3
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Radio Mirchi" ,Radio Mirchi
http://peridot.streamguys.com:7150/Mirchi

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Radio Schizoid - Chillout / Ambient" tvg-logo="https://dl.dropbox.com/s/etxv1fmhxeyl3oy/RadioLive.gif" group-title=“FM Radio",Radio Schizoid - Chillout / Ambient
http://94.130.113.214:8000/chill
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Radio Schizoid - Dub Techno" tvg-logo="https://dl.dropbox.com/s/etxv1fmhxeyl3oy/RadioLive.gif" group-title=“FM Radio",Radio Schizoid - Dub Techno
http://94.130.113.214:8000/dubtechno
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Radio Schizoid - Progressive Psychedelic Trance" tvg-logo="https://dl.dropbox.com/s/etxv1fmhxeyl3oy/RadioLive.gif" group-title=“FM Radio",Radio Schizoid - Progressive Psychedelic Trance
http://94.130.113.214:8000/prog
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Radio Today" tvg-logo="https://dl.dropbox.com/s/etxv1fmhxeyl3oy/RadioLive.gif" group-title=“FM Radio",Radio Today
http://node-24.zeno.fm/0zha3rfq02quv?rj-ttl=5&rj-tok=AAABdMQIscsAumYfZ0oUroNvhQ
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Radio Today(89.6)" tvg-logo="" group-title=“FM Radio",Radio Today(89.6)
http://node-03.zeno.fm/0zha3rfq02quv?@IPTVSolution
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="SaRaHa" tvg-logo="https://dl.dropbox.com/s/etxv1fmhxeyl3oy/RadioLive.gif" group-title=“FM Radio",SaRaHa
http://node-30.zeno.fm/5hx71hbuqhruv?listening-from-radio-garden=1601016201300&rj-tok=AAABdMQJqSIA6Gf4cI6DZUMhdA&rj-ttl=5
#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Suno FM 102." tvg-logo="https://dl.dropbox.com/s/etxv1fmhxeyl3oy/RadioLive.gif" group-title=“FM Radio",Suno FM 102.
http://51.255.235.165:5476/;stream.mp3?listening-from-radio-garden=1601020600078

#EXTINF:-1 tvg-id="(no tvg-id)" tvg-name="Ujala Radio" tvg-logo="https://dl.dropbox.com/s/etxv1fmhxeyl3oy/RadioLive.gif" group-title=“FM Radio",Ujala Radio
http://stream2.ujala.nl/stream/2/listen.mp3

