#EXTM3U
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/2708/logo/240x240/mobile_logo_399602001643008831.png" group-title="Live",Toffee Live 1
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=sports_live_01_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/2889/logo/240x240/mobile_logo_511945001643008894.png" group-title="Live",Toffee Live 2
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=sports_live_02_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/603/logo/115x115/mobile_logo_524057001567842834.png" group-title="HD",Sony Ten 1
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=sony_ten1_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/604/logo/115x115/mobile_logo_995268001567842888.png" group-title="HD",Sony Ten 2
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=sony_ten2_hd_720&user=d7ab3df0441020890b5655d25e64165e
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/2418/logo/240x240/mobile_logo_060335001610628658.png" group-title="HD",Sony Ten 3
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=sony_ten3_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/606/logo/115x115/mobile_logo_532142001572844781.png" group-title="HD",Sony Six
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=sony_six_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/644/logo/240x240/mobile_logo_042661001635168980.png" group-title="HD",Zee TV HD
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=zee_tv_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/602/logo/240x240/mobile_logo_226035001584535399.png" group-title="HD",Sony Entertainmnt HD
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=sony_entertainmnt_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/641/logo/115x115/mobile_logo_602468001571288709.png" group-title="HD",SET MAX HD
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=set_max_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/2419/logo/240x240/mobile_logo_783997001610629373.png" group-title="HD",Sony PIX HD
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=sony_pix_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/2420/logo/240x240/mobile_logo_091920001610629573.png" group-title="HD",Sony SAB HD
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=sony_sab_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/670/logo/240x240/mobile_logo_960661001610174299.png" group-title="HD",Sony BBC Earth HD
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=sony_bbc_earth_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/801/logo/240x240/mobile_logo_898113001635169566.png" group-title="HD",&TV HD
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=and_tv_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
#EXTINF:-1 tvg-logo="https://images.toffeelive.com/images/program/804/logo/240x240/mobile_logo_572559001635168920.png" group-title="HD",Zee CINEMA HD
https://streamer-1.toffeelive.com/?bitrate=1024000&channel=zee_cinema_hd_720&user=ec2ecbd2dcb21b4340ae9704d00007fe
